# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enroll.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 520)
        MainWindow.setMinimumSize(QtCore.QSize(470, 520))
        MainWindow.setMaximumSize(QtCore.QSize(470, 520))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 20, 211, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 90, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 161, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 161, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 240, 101, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 141, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 340, 131, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 390, 171, 21))
        self.label_8.setObjectName("label_8")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(180, 80, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.inum = QtWidgets.QLineEdit(self.centralwidget)
        self.inum.setGeometry(QtCore.QRect(180, 130, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inum.setFont(font)
        self.inum.setReadOnly(True)
        self.inum.setObjectName("inum")
        self.snum = QtWidgets.QLineEdit(self.centralwidget)
        self.snum.setGeometry(QtCore.QRect(180, 180, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.snum.setFont(font)
        self.snum.setObjectName("snum")
        self.prog = QtWidgets.QLineEdit(self.centralwidget)
        self.prog.setGeometry(QtCore.QRect(180, 230, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.prog.setFont(font)
        self.prog.setObjectName("prog")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(180, 280, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.pnum = QtWidgets.QLineEdit(self.centralwidget)
        self.pnum.setGeometry(QtCore.QRect(180, 330, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pnum.setFont(font)
        self.pnum.setObjectName("pnum")
        self.total = QtWidgets.QLineEdit(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(180, 380, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.total.setFont(font)
        self.total.setObjectName("total")
        self.bcancel = QtWidgets.QPushButton(self.centralwidget)
        self.bcancel.setGeometry(QtCore.QRect(330, 450, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bcancel.setFont(font)
        self.bcancel.setObjectName("bcancel")
        self.bsave = QtWidgets.QPushButton(self.centralwidget)
        self.bsave.setGeometry(QtCore.QRect(190, 450, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bsave.setFont(font)
        self.bsave.setObjectName("bsave")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ENROLL USER"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">INFORMATION</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">NAME:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">INDEX NUMBER:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">STUDENT NUMBER:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">PROGRAM:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">EMAIL ADDRESS:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">PHONE NUMBER:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">TOTAL WORK HOURS:</span></p></body></html>"))
        self.bcancel.setText(_translate("MainWindow", "CANCEL"))
        self.bsave.setText(_translate("MainWindow", "SAVE"))
