# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'users.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 600)
        MainWindow.setMinimumSize(QtCore.QSize(550, 600))
        MainWindow.setMaximumSize(QtCore.QSize(550, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 110, 211, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 180, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 230, 161, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 280, 161, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 330, 101, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 380, 141, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 430, 131, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 480, 200, 21))
        self.label_8.setObjectName("label_8")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(210, 170, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setReadOnly(True)
        self.name.setObjectName("name")
        self.inum = QtWidgets.QLineEdit(self.centralwidget)
        self.inum.setGeometry(QtCore.QRect(210, 220, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inum.setFont(font)
        self.inum.setReadOnly(True)
        self.inum.setObjectName("inum")
        self.snum = QtWidgets.QLineEdit(self.centralwidget)
        self.snum.setGeometry(QtCore.QRect(210, 270, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.snum.setFont(font)
        self.snum.setReadOnly(True)
        self.snum.setObjectName("snum")
        self.prog = QtWidgets.QLineEdit(self.centralwidget)
        self.prog.setGeometry(QtCore.QRect(210, 320, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.prog.setFont(font)
        self.prog.setReadOnly(True)
        self.prog.setObjectName("prog")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(210, 370, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email.setFont(font)
        self.email.setReadOnly(True)
        self.email.setObjectName("email")
        self.pnum = QtWidgets.QLineEdit(self.centralwidget)
        self.pnum.setGeometry(QtCore.QRect(210, 420, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pnum.setFont(font)
        self.pnum.setReadOnly(True)
        self.pnum.setObjectName("pnum")
        self.total = QtWidgets.QLineEdit(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(210, 470, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.total.setFont(font)
        self.total.setReadOnly(True)
        self.total.setObjectName("total")
        self.bback = QtWidgets.QPushButton(self.centralwidget)
        self.bback.setGeometry(QtCore.QRect(400, 540, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.bback.setFont(font)
        self.bback.setObjectName("bback")
        self.ename = QtWidgets.QPushButton(self.centralwidget)
        self.ename.setGeometry(QtCore.QRect(490, 170, 51, 31))
        self.ename.setObjectName("ename")
        self.esn = QtWidgets.QPushButton(self.centralwidget)
        self.esn.setGeometry(QtCore.QRect(490, 270, 51, 31))
        self.esn.setObjectName("esn")
        self.eprog = QtWidgets.QPushButton(self.centralwidget)
        self.eprog.setGeometry(QtCore.QRect(490, 320, 51, 31))
        self.eprog.setObjectName("eprog")
        self.eemail = QtWidgets.QPushButton(self.centralwidget)
        self.eemail.setGeometry(QtCore.QRect(490, 370, 51, 31))
        self.eemail.setObjectName("eemail")
        self.epn = QtWidgets.QPushButton(self.centralwidget)
        self.epn.setGeometry(QtCore.QRect(490, 420, 51, 31))
        self.epn.setObjectName("epn")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 40, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 50, 141, 21))
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MANAGE USERS"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">INFORMATION</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">NAME:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">INDEX NUMBER:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">STUDENT NUMBER:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">PROGRAM:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">EMAIL ADDRESS:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">PHONE NUMBER:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">HOURS ACCOMPLISHED:</span></p></body></html>"))
        self.bback.setText(_translate("MainWindow", "BACK"))
        self.ename.setText(_translate("MainWindow", "EDIT"))
        self.esn.setText(_translate("MainWindow", "EDIT"))
        self.eprog.setText(_translate("MainWindow", "EDIT"))
        self.eemail.setText(_translate("MainWindow", "EDIT"))
        self.epn.setText(_translate("MainWindow", "EDIT"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">SELECT STUDENT:</span></p></body></html>"))
